services:

  # External dependencies
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "/opt/efdp/mailu/redis:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "serverip:8088:80"
      - "serverip:4433:443"
      - "serverip:25:25"
      - "serverip:465:465"
      - "serverip:587:587"
      - "serverip:110:110"
      - "serverip:995:995"
      - "serverip:143:143"
      - "serverip:993:993"
      - "serverip:4190:4190"
    networks:
      - default
      - webmail
    volumes:
      - "/opt/efdp/mailu/certs:/certs"
      - "/opt/efdp/mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "/opt/efdp/mailu/data:/data"
      - "/opt/efdp/mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "/opt/efdp/mailu/mail:/mail"
      - "/opt/efdp/mailu/overrides/dovecot:/overrides:ro"
    networks:
      - default
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "/opt/efdp/mailu/mailqueue:/queue"
      - "/opt/efdp/mailu/overrides/postfix:/overrides:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254



  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2024.06}
    hostname: antispam
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
    volumes:
      - "/opt/efdp/mailu/filter:/var/lib/rspamd"
      - "/opt/efdp/mailu/overrides/rspamd:/overrides:ro"
    depends_on:
      - front
      - redis
      - resolver
    dns:
      - 192.168.203.254

  # Optional services

  gofish:
    image: gophish/gophish
    container_name: gophish
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - default
    ports:
      - "0.0.0.0:3333:3333"
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443" #如使用TLS开启443的绑定
      - "0.0.0.0:8080:8080"
    volumes:
      - "/opt/efdp/gophish/gophish.db:/opt/gophish/gophish.db" #持久化数据
      - "/opt/efdp/gophish/certs:/opt/gophish/certs" #证书
      - "/opt/efdp/gophish/config.json:/opt/gophish/config.json" #配置文件
    environment:
      - GOPHISH_INITIAL_ADMIN_PASSWORD=gppassword
    dns:
      - 192.168.203.254

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: /opt/efdp/mailu/mailu.env
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "/opt/efdp/mailu/webmail:/data"
      - "/opt/efdp/mailu/overrides/snappymail:/overrides:ro"
    networks:
      - webmail
    depends_on:
      - front

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  webmail:
    driver: bridge
